import type { Metadata } from "next";
import { ThemeProvider } from "@/providers/theme-provider"
import { DM_Sans } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import ModalProvider from "@/providers/modal-provider";

const dmSans = DM_Sans({ subsets: ['latin'], weight: ['400', '500', '700'] });

export const metadata: Metadata = {
  title: "Next App Builder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

      <html lang="en" suppressHydrationWarning>
        <body className={dmSans.className}>

       
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ModalProvider>
            {children}
            <Toaster />
            {/* <SonnarToaster position="bottom-left" /> */}
          </ModalProvider>
        </ThemeProvider>
        </body>
      </html>
  );
}
